pipeline:
  identifier: Build_cmiller241_JenkinsTest_1715118242321
  name: Build JenkinsTest
  orgIdentifier: default
  projectIdentifier: HelloWorld2
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1715118214843
        repoName: cmiller241/JenkinsTest
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
